name: CI Pipeline HTML-CSS-JS

on:
  push:
    branches: [ "master" ]   # Se ejecuta cada vez que subes cambios a la rama main
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Validar estructura de archivos
      run: |
        echo "Verificando archivos HTML, CSS y JS..."
        ls -R

    - name: Prueba simple de HTML
      run: |
        if grep -q "<html>" index.html; then
          echo "Archivo HTML válido"
        else
          echo "Error: falta etiqueta <html>"
          exit 1
        fi
    - name: Deploy a GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./   # Carpeta donde están tus archivos HTML, CSS y JS
